### ISSUE TITLE
How to Submit a contest to Lambda Function?

### ISSUE THREAD

**Issue by rafaelcarvalhoj** [NimbusJudgeOrganization/Nimbus-Judge-Organization#11]
## Description
We need to automatically deploy our contests in the cloud. The idea is to build all the contest requirements in the Nimbus Judge API and deploy using either [Terraform](https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#usage) or [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-lambda.html). I recommend Terraform because the Chalice API provides a pre-built integration with Terraform, making it less complicated. We just need to edit the deployment file.

## Tasks
- [ ] Study Terraform or CloudFormation in Lambda Context

## Tests
- [ ] Run a Iaas(Infrastruct as a Code) for automatic deploy a AWS Lambda Function
- [ ] Deploy a Lambda Function with diferent runtime, try [ubi-8 container image](https://hub.docker.com/r/redhat/ubi8-micro/tags)

## Resources
I've attached a Chalice Terraform build file. Try to guide your studies based on the Chalice pre-build.
[terraform.zip](https://github.com/NimbusJudgeOrganization/Nimbus-Judge-Organization/files/15153474/terraform.zip)
