### ISSUE TITLE
Lambda Judge Base Image

### ISSUE THREAD

**Issue by rafaelcarvalhoj** [NimbusJudgeOrganization/Nimbus-Judge-Organization#12]
## Description
This issue concerns the base image that we will use in our serverless judge. Since AWS Lambda supports custom runtimes, we can build our own Docker image with all Micro-Judge dependencies. The idea is to use a tiny base container image, like ubi8-micro from Red Hat, and create the Micro-Judge image that will be used to build the Lambda contests.

## Tasks
- [ ] ubi8-Nimbus-Judge Docker file based on [ubuntu Nimbus-Judge](https://github.com/NimbusJudgeOrganization/Nimbus-Judge-Organization/tree/main/Judge/Docker).
- [ ] Install [python requiriments](https://github.com/NimbusJudgeOrganization/API_MicroJudge/tree/chalice) for the Chalice API.
- [ ] Import Chalice API to Dockerfile build.

## Tests
- [ ] Execute Chalice API with ubi8-Nimbus-Judge base image.
- [ ] Judge **fatorial** and other questions.

## Links
[Lambda Python base image](https://github.com/aws/aws-lambda-base-images/tree/python3.10)
[Red Hat ubi8-micro image](https://hub.docker.com/r/redhat/ubi8-micro/tags)
