### ISSUE TITLE
Fix Judge dependency

### ISSUE THREAD

**Issue by rafaelcarvalhoj** [NimbusJudgeOrganization/Nimbus-Judge-Organization#4]
## Description
The Judge isn't working due to the system initialization configuration issue, so we need to conduct the judging process in a clear container with only the necessary packages.

## Tasks
- [ ] Create a Script to initialize the micro-judge container.
- [x] Create full documentation for the judge.
## Tests
- [ ] Run a Dockerfile that execute the build-and-test.sh without any additional command
