### ISSUE TITLE
 Create a MojTools containerization

### ISSUE THREAD

**Issue by johan-rocha** [NimbusJudgeOrganization/Nimbus-Judge-Organization#6]
##  Create a MojTools containerization
In this task, the objective is automate MojTools package dependencies installation in dockerfile .

## Tasks
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Verify all dependencies
- [x] Check dependencies versions
- [x] Create a Dockerfile
- [ ] usern remap privilegies for "time" linux command

## Tests/rating
- [x] Check examples in run time
- [x] Run Dockerfile and container in different platforms
- [ ] Test in Cloud
