### ISSUE TITLE
Nimbus Judge Plataform Database Modeling

### ISSUE THREAD

**Issue by rafaelcarvalhoj** [NimbusJudgeOrganization/Nimbus-Judge-Organization#7]
## Description
This task is responsible for modeling the database schema. You should consider the use cases for the NJ platform. Some of these use cases include: Login, Creating Users per contest, Linking a User account with a contest, Creating a contest, Adding questions to a contest, Defining a contest administrator (professor), Checking contest submission and more...  

## Tasks
- [x] Conceptual Data Model (Diagram in any plataform)
- [x] Normalization (Max norm)
- [ ] **EXTRA**: Transform Conceptual Data Model in SQL (for practice SQL)
